sudo: required
language: node_js
install:
  - npm i
cache: npm
node_js:
  - "node"
branches:
  only:
    - master
    - test
    - /^greenkeeper/.*$/
jobs:
  include:
    - stage: unit tests
      script: yarn run test
      after_success: yarn run coverage
    - stage: build
      script: yarn run build
