sudo: required
language: node_js
env:
  - BUILD_ENV=ci
install:
  - npm i
cache: npm
node_js:
  - "node"
branches:
  only:
    - master
    - test
    - /^greenkeeper/.*$/
jobs:
  include:
    - stage: unit tests
      script: npm run test
      after_success: npm run coverage
    - stage: build
      script: npm run build
